"""Building blocks shared by every exporter, so all context files agree."""

from __future__ import annotations

from typing import List, Tuple

from project_md.core.knowledge_base import get_trap
from project_md.core.models import Finding, Platform, PreflightReport, Severity


def dead_ends(report: PreflightReport) -> List[Tuple[str, str, str, str]]:
    """(trap id, what not to do, why, what to use instead), most severe first."""
    trap_findings = sorted((f for f in report.findings if f.trap_id), key=lambda f: (f.severity.rank, f.trap_id))
    rows = []
    for finding in trap_findings:
        trap = get_trap(finding.trap_id)
        rows.append((trap.id, trap.trap, trap.why_it_fails, "; ".join(trap.recommended)))
    return rows


def layer_rules(report: PreflightReport) -> List[str]:
    return [
        f"{layer.name} may import only: {', '.join(layer.may_depend_on) or 'nothing'}. {layer.responsibility}"
        for layer in report.layers
    ]


def stack_lines(report: PreflightReport) -> List[str]:
    return [f"{c.role}: {c.choice}" for c in report.stack.components]


def open_issues(report: PreflightReport) -> List[Finding]:
    """Unresolved warnings a human must decide on (the REVIEW items)."""
    return [f for f in report.findings if not f.mitigated and not f.trap_id and f.severity is not Severity.INFO]


def guidance(report: PreflightReport) -> List[Finding]:
    """Standing rules for the assistant: resolved findings that aren't stack/contract decisions."""
    return [f for f in report.findings if f.payload is None and not f.trap_id and f.mitigated]


def commands(report: PreflightReport) -> List[Tuple[str, str]]:
    """(purpose, command) cheat sheet derived from the chosen stack."""
    python = report.stack.language == "Python"
    roles = {c.role for c in report.stack.components}
    # Web, mobile and desktop clients are always JS/TS (Next.js, Expo, Tauri), even over a Python backend.
    client_cmds: List[Tuple[str, str]] = []
    if "Web frontend" in roles:
        client_cmds.append(("Run web app", "npm run dev"))
    if "Mobile app" in roles:
        client_cmds.append(("Run mobile app", "npx expo start"))
    if "Desktop app" in roles:
        client_cmds.append(("Run desktop app", "npm run tauri dev"))

    cmds: List[Tuple[str, str]] = []
    if python:
        cmds.append(("Set up", "python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt"))
        if "Backend API" in roles:
            cmds.append(("Run API", "uvicorn app.main:app --reload"))
        if Platform.CLI in report.intent.platforms:
            cmds.append(("Run CLI", "python3 -m app"))
        if client_cmds:
            cmds.append(("Set up frontend", "cd frontend && npm install"))
            cmds += [(purpose, f"cd frontend && {cmd}") for purpose, cmd in client_cmds]
        cmds += [("Test", "python3 -m pytest"), ("Lint", "ruff check .")]
    else:
        cmds.append(("Set up", "npm install"))
        if "Backend API" in roles and "Web frontend" not in roles:
            cmds.append(("Run API", "npm run dev"))
        cmds += client_cmds
        cmds += [("Test", "npm test"), ("Lint + typecheck", "npm run lint && npx tsc --noEmit")]
    return cmds


def typing_rule(report: PreflightReport) -> str:
    if report.stack.language == "Python":
        return "Type-hint every function. Validate all external input with Pydantic models; never pass raw dicts between layers."
    return "TypeScript strict mode; no `any`. Validate all external input with Zod schemas and infer types from them."


def header_note(target: str) -> str:
    return (
        f"<!-- Generated by PROJECT.MD for {target}. PROJECT.md is the source of truth; "
        "regenerate rather than editing by hand. -->"
    )
